version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app
    overwrite: yes
permissions:
  - object:  /home/ec2-user/app
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  AfterInstall:
    - location: start.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: switch.sh
      timeout: 300
      runas: root