= Hyper Link
backtony.github.io(Rest Docs)
:doctype: book
:icons: font
:source-highlighter: highlightjs // 문서에 표기되는 코드들의 하이라이팅을 highlightjs를 사용
:toc: left
:toclevels: 4
:sectlinks:

== Content

=== 조회수 갱신

operation::ContentControllerTest/addInquiryOfContent[snippets='http-request,http-response,response-fields']

=== 검색

operation::ContentControllerTest/search[snippets='http-request,http-response,response-fields']

=== 전체 카테고리 조회

operation::ContentControllerTest/retrieveAllCategory[snippets="http-request,http-response"]

=== 카테고리별 조회

operation::ContentControllerTest/retrieve[snippets="http-request,http-response"]

== MemberContent

=== 북마크 추가/삭제

operation::MemberContentController/includeCreateOrDeleteBookmark[snippets='http-request,http-response']

== 북마크 조회

operation::MemberContentController/getBookmarks[snippets='http-request,http-response']

== Member

=== 회원가입

operation::members/signup[snippets='http-request,http-response,response-fields']

=== 로그인

operation::members/login[snippets='http-request,http-response,response-fields']

=== 내정보 조회

operation::members/mypage[snippets='http-request,http-response,response-fields']

=== 프로필 변경

operation::members/update[snippets='http-request,http-response,response-fields']

== History

=== 히스토리 전체 내역 조회

operation::MemberHistoryControllerTest/getAllHistory[snippets='http-request,http-response,response-fields']

== Creator

=== 비추천 크리에이터 추가

operation::CreatorControllerTest/notRecommend[snippets='http-request,http-response']

=== 크리에이터 상세 조회

operation::CreatorControllerTest/retrieveCreatorDetail[snippets='http-request,http-response']

=== 크리에이터 조회

operation::CreatorControllerTest/retrieveCreator[snippets='http-request,http-response']

== Subscription

=== 크리에이터 구독/구독 취소

operation::SubscriptionControllerTest/subscribeOrUnsubscribeCreator[snippets='http-request,http-response']

=== 구독 피드 카테고리별 조회

operation::SubscriptionControllerTest/retrieveByCategory[snippets='http-request,http-response']

=== 구독 피드 전체 카테고리 조회

operation::SubscriptionControllerTest/retrieveAllCategory[snippets='http-request,http-response']

== Daily-Briefing

=== 데일리 브리핑 조회

operation::DailyBriefingControllerTest/getDailyBriefing[snippets='http-request,http-response']

== Admin

=== 크리에이터 조회

operation::CreatorControllerTest/retrieveCreatorsAdmin['http-request,http-response']

=== 크리에이터 삭제

operation::CreatorControllerTest/deleteCreator[snippets='http-request,http-response']

=== 크리에이터 추가

operation::CreatorControllerTest/enrollCreator[snippets='http-request,http-response']

=== 비활성 컨텐츠 조회

operation::ContentControllerTest/retrieveInactiveContents[snippets='http-request,http-response']

=== 컨텐츠 활성화

operation::ContentControllerTest/activateContent[snippets='http-request,http-response']

=== 최근 7일 카테고리별 조회수 조회

operation::AdminController/countViewCountByCategory[snippets='http-request,http-response']

== AttentionCategory

=== 관심카테고리 변경

operation::Attention-category/update[snippets='http-request,http-response,response-fields']

=== 관심 카테고리 조회

operation::Attention-category/get[snippets='http-request,http-response,response-fields']

== Company

=== 회사 이메일 인증번호 요청

operation::company/auth[snippets='http-request,http-response']

=== isUsingRecommend 값이 false인 회사 목록 가져오기(admin)

operation::company/getCompanyPage[snippets='http-request,http-response']

=== 회사 이메일 인증번호 확인 및 등록

operation::company/verification[snippets='http-request,http-response']

=== 회사를 추천 서비스에 추가하는 api

operation::company/changeIsUsingRecommend[snippets='http-request,http-response']

=== 회사 이름 변경 api(admin)

operation::company/changeName[snippets='http-request,http-response']
