= Hyper Link
backtony.github.io(Rest Docs)
:doctype: book
:icons: font
:source-highlighter: highlightjs // 문서에 표기되는 코드들의 하이라이팅을 highlightjs를 사용
:toc: left
:toclevels: 4
:sectlinks:

== Content

=== 조회수 갱신

operation::ContentControllerTest/addInquiryOfContent[snippets='http-request,http-response,response-fields']

=== 검색

operation::ContentControllerTest/search[snippets='http-request,http-response,response-fields']

=== 전체 카테고리 조회

operation::ContentControllerTest/retrieveAllCategory[snippets="http-request,http-response"]

=== 카테고리별 조회

operation::ContentControllerTest/retrieve[snippets="http-request,http-response"]

== MemberContent

=== 북마크 추가/삭제

operation::MemberContentController/includeCreateOrDeleteBookmark[snippets='http-request,http-response']

== Member

=== 회원가입

operation::members/signup[snippets='http-request,http-response,response-fields']

=== 로그인

operation::members/login[snippets='http-request,http-response,response-fields']

=== 내정보 조회

operation::members/mypage[snippets='http-request,http-response,response-fields']

=== 관심목록 변경

operation::members/attention-category[snippets='http-request,http-response,response-fields']

=== 프로필 변경

operation::members/update[snippets='http-request,http-response,response-fields']

== History

=== 히스토리 전체 내역 조회

operation::MemberHistoryControllerTest/getAllHistory[snippets='http-request,http-response,response-fields']

== Creator

=== 비추천 크리에이터 추가

operation::CreatorControllerTest/notRecommend[snippets='http-request,http-response']

== Subscription

=== 크리에이터 구독/구독 취소

operation::SubscriptionControllerTest/subscribeOrUnsubscribeCreator[snippets='http-request,http-response']

=== 구독 피드 카테고리별 조회

operation::SubscriptionControllerTest/retrieveByCategory[snippets='http-request,http-response']

=== 구독 피드 전체 카테고리 조회

operation::SubscriptionControllerTest/retrieveAllCategory[snippets='http-request,http-response']

== Admin

=== 크리에이터 삭제

operation::CreatorControllerTest/deleteCreator[snippets='http-request,http-response']

=== 크리에이터 추가

operation::CreatorControllerTest/enrollCreator[snippets='http-request,http-response']

=== 컨텐츠 활성화

operation::ContentControllerTest/activateContent[snippets='http-request,http-response']

== Company

=== 이메일 인증번호 요청

operation::company/auth[snippets='http-request,http-response']