= Hyper Link
backtony.github.io(Rest Docs)
:doctype: book
:icons: font
:source-highlighter: highlightjs // 문서에 표기되는 코드들의 하이라이팅을 highlightjs를 사용
:toc: left
:toclevels: 4
:sectlinks:

== Content

=== 조회수 갱신

operation::ContentControllerTest/addInquiryOfContent[snippets='http-request,http-response,response-fields']

=== 검색

operation::ContentControllerTest/search[snippets='http-request,http-response,response-fields']

== MemberContent

=== 북마크 추가/삭제

operation::MemberContentController/includeCreateOrDeleteBookmark[snippets='http-request,http-response']

== Member

=== 회원가입

=== /members/signup

operation::members/signup[snippets='http-request,http-response,response-fields']

=== 로그인

=== /members/login

operation::members/login[snippets='http-request,http-response,response-fields']

== History
=== 히스토리 전체 내역 조회
operation::MemberHistoryControllerTest/getAllHistory[snippets='http-request,http-response,response-fields']

== Creator
=== 비추천 크리에이터 추가

operation::CreatorControllerTest/notRecommend[snippets='http-request,http-response']

=== 크리에이터 삭제
operation::CreatorControllerTest/deleteCreator[snippets='http-request,http-response']

=== 크리에이터 추가
operation::CreatorControllerTest/enrollCreator[snippets='http-request,http-response']