# This is a basic workflow to help you get started with Actions
name: hyperlink-production CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  pull_request:
    branches: main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-prod:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: JDK 17 설치
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Redis 설치
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: '6.x'
          run: redis-cli ping

      - name: application-prod.yml 생성
        run: |
          mkdir src/test/resources
          touch src/main/resources/application.yml
          touch src/test/resources/application.yml

      - name: application-prod.yml 설정
        run: echo "${{secrets.APPLICATIONPRODUCTION}}" | base64 --decode > src/main/resources/application.yml

      - name: application-test.yml 설정
        run: echo "${{secrets.APPLICATIONTEST}}" | base64 --decode > src/test/resources/application.yml

      - name: ./gradlew 권한 설정
        run: chmod +x ./gradlew

      - name: 빌드
        run: ./gradlew clean build -x jacocoTestCoverageVerification